elementary/stylesheet

.gitignore, .stylelintrc.json, .travis.yml, package.json
This adds `stylelint` package for CSS linting. I used the same configuration that elementary/website uses minus a couple of settings that interfere with GTK.
For testing locally you will need `npm` installed. If you have done any work on website, or node projects this should already be installed. Then run `npm install` to grab `stylelint`. You will only need to do this once. Then run `npm test` and it will lint all the CSS files.
=> add inital configuration for ci tests

gtk-3.0/apps.css, gtk-3.0/gtk-widgets.css
Had to remove `to bottom` to make the linter happy for some reason. It's okay because the default gradient direction is `to bottom` so no loss.
=> make menubar transparent if it's inside a titlebar

gtk-3.0/apps.css, gtk-3.0/gtk-widgets.css
This branch changes the style of `default-decoration` to match that of `titlebar.compact`.
Up until this point, the stylesheet has been mostly built around the assumption that a titlebar has a toolbar below it. However, this isn't always the case. Changing the style in this way should make some non-native apps look nicer as well as not require the explicit use of `Gtk.Headerbar` if no toolbar is needed.
Please test this branch thoroughly for adverse effects before merging :)
**Before:**
**After:**
=> Default decoration

gtk-3.0/gtk-widgets.css
Fixes #69 
Just some ridiculous specificity stuff we have to do because `:not` isn't a thing in gtk3.18
=> Give stackswitcher image buttons in titlebars a border

gtk-3.0/gtk-widgets.css
There's a bunch of crap to try to undo the `.action-bar .button` selector but the smart thing to do is just make that only select `.action-bar .button.image-button`
=> only make image-buttons flat in action bars

gtk-3.0/granite-widgets.css
This fixes a glitch where the border will transition from black once the element is :checked
=> set card border to transparent to fix glitchy border transitions

gtk-3.0/granite-widgets.css, gtk-3.0/gtk-widgets-dark.css, gtk-3.0/gtk-widgets.css
* Greatly reduces lines of code used to draw infobars
* Flatter design
* Fixes close button color in dark stylesheet
* Fixes text shadow in dark stylesheet
* Fixes #75 
Before:
After:
=> Make InfoBar flatter

gtk-3.0/apps.css
Depends on having a Terminal release that [contains this fix](https://code.launchpad.net/~elementary-apps/pantheon-terminal/background-css/+merge/315308)
=> remove Terminal CSS

gtk-3.0/gtk-widgets.css
Adjust border colors a bit. Use shade for warning button border to make the color less muddy looking.
Before:
After:
=> Refine infobar styles

gtk-3.0/gtk-widgets.css
I made a mistake, base color looks weird.
Before:
After:
=> Infobar: Use bg color as default instead of base color

gtk-3.0/gtk-widgets.css
Not 100% where this belongs; it is an explicit property on Gtk.TextView but could also definitely be a class used on any widget. Added with the other misc stuff for now.
Fixes #94
=> Add .monospace support

gtk-3.22/gtk-widgets.css
Fixes the background clipping in `popover.menu` as seen in gtk3-widget-factory
=> Fix aggressive clipping on popover.menu

gtk-3.22/gtk-widgets.css
We're going to inherit color unless we override in specific widgets. This fixes image color in AppCenter for example
=> Images inherit color

gtk-3.22/gtk-widgets.css
Simplify and make tooltips the same opacity as overlay bars
=> Make tooltips more opaque

gtk-3.22/gtk-widgets.css
* Remove selectors from 3.18
* Use not selector to simplify button style overrides
* Simplify RTL support
* Use .up and .down instead of :first-child and :last-child
* Fix margins
* Make sure to fully clear entry styles
=> Rewrite spinbutton

gtk-3.22/assets/check-active.svg, gtk-3.22/assets/check-active@2.svg, gtk-3.22/gtk-widgets.css
Replaces icon shadow in the image with one in CSS. This means checkbox now fully respects `colorAccent`:
=> Check, Radio: use icon-shadow

gtk-3.22/gtk-widgets.css
Make sure that we're selecting the separator that comes with the pane and not other separators inside each side of the pane
=> Make pane sep style selector more specific

gtk-3.22/gtk-widgets.css
This applies to `button.menuitem` which we use to emulate menu items in popovers like wingpanel indicators. Prevents having to override button styles
=> Don't apply button styles to menuitem buttons

gtk-3.22/gtk-widgets.css
Fixes an incorrect selection. Turns out `mark` is actually a container that also can have a label in it
=> select indicator, not the whole mark container

gtk-3.22/gtk-widgets.css
* Remove old 3.18 `GtkModelButton` selector
* Apply the same styles for `menuitem`, `.menuitem`, and `modelbutton` no matter their container (`popover`, `popup`, or `menu`)
* Selectors in alphabetical order
* Fix accelerator selector
=> Rewrite menuitems and modelbuttons

gtk-3.22/gtk-widgets.css
Turns out that using `:not` makes this selector more specific than `button.flat` and other button classes and breaks all the things. So it's actually safer to override
=> Don't use :not for menuitem

gtk-3.22/gtk-widgets.css
Fixes a bug with `window.rounded:backdrop .inline-toolbar`. Don't see any reason why we'd set border radius here since we should inherit radius from the element already
=> don't set radius in inline-toolbar

gtk-3.22/gtk-widgets.css
Make sure we're only styling "windows" that have this class and not buttons, popovers, etc
=> make menu and popup class selectors more specific

gtk-3.0/gtk-widgets.css, gtk-3.22/gtk-widgets.css
Fixes #166 
Sidebar text color contrast now passes WCAG AAA. This branch fixes both Loki and Juno
Before:
After:
=> increase sidebar text contrast

gtk-3.22/gtk-widgets-dark.css
`.popup` class is used for more than just menus, so we need to be more specific that we're selecting menu "windows"
While we're here, make the outline a bit darker
=> Make dark selector for popup more specific

gtk-3.22/gtk-widgets.css
Fixes #184 
Flattens titlebars and updates toolbars, notebooks, actionbars, and search bars to match. This works a bit more nicely with brand colors, which start to get muddy with the use of `shade ()`
This probably needs extensive testing
Before:
After:
=> Flatter chrome

gtk-3.22/gtk-widgets.css
Mutter now gives us information about which side of the display a window is tiled against. Use that to fix a regression which caused square maximized windows and to only square the inside edges of windows
=> Use new tiled classes

gtk-3.22/granite-widgets.css
Adds a Silver100 stop to the temperature scale to better reflect how temperature is being visualized on other platforms. Plus, the white just makes the transition look better :wink: 
Example: 
- http://content.hwigroup.net/images/products_xl/169930/18/philips-hue-connected-bulb-starter-pack-e27.jpg
=> Added Silver100 to temperature scale

gtk-3.22/gtk-dark.css, gtk-3.22/gtk-widgets-dark.css, gtk-3.22/gtk-widgets.css
* Use a color from the palette for text color
* Get rid of legacy selector `EggListBox`
* Use `mix` for toolbar  and titlebar image colors that work better on light and dark stylesheets
* Make the selector for toolbar and titlebar images less specific so that it keeps buttons and plain Gtk.Images matching
=> misc dark style fixes

gtk-3.22/granite-widgets.css
This fixes a regression from Loki to Juno with the description text size in welcome buttons
**Before:**
**After:**
=> Fix incorrect units on welcome buttons

gtk-3.22/gtk-widgets.css
Gtk.ImageMenuItem is now deprecated and the docs recommend packing images inside a container with the label. The problem is this fucks up the alignment, so here we do some CSS magic to fix it
=> Fix menuitem image placement

gtk-3.22/gtk-widgets.css
* round correct corners for RTL or inverted widgets
* remove highlight margin for inner border for more accurate Granite Seekbar
* display fill level property, when set
before:
after:
This only fixes 3.22 version. There are similar issues for gtk-3.0. Is that version still active and should it be fixed? I haven't checked 2.0.
I'm not sure if style for fill level is ok, i just added some color to it so that it's displayed. And also since highlight is partly transparent, fill level makes it more dark.
Let me know if anyone wants code for this test app.
=> Fix GtkScale rounded borders and margin, show fill level

gtk-3.22/granite-widgets.css, gtk-3.22/gtk-widgets.css, gtk-3.22/gtk.css
Fixes #263
Fixes a bit of fuckery around setting the text color and button color for branded titlebars
**Before:**
**After:**
=> Headerbar brand fixes

gtk-3.22/granite-widgets.css
=> Add a class to easy give text and images accent color

gtk-3.22/gtk-widgets-dark.css, gtk-3.22/gtk-widgets.css
By some unknown reason GtkTextView background is not defined anywhere. See #249.
Even CSS editor in GtkDebugger (by Ctrl+Shift+D) is affected.
There is only least change, necessary to just make it working. Looking to Minwaita as example, you may find much more detailed definitions, such as for various text styles. I did not change gtk-3.0 because can't test for gtk+ <= gtk-3.20 (gentoo portage tree has removed everything lower then 3.22).
=> Define background for GtkTextView (fix #249)

gtk-3.22/gtk-widgets.css
Fixes #289 
Looks like for some reason Gtk.MessageDialog was not using the symbolic icon variant. Forcing titlebuttons to be symbolic fixes this
=> Force titlebuttons symbolic

gtk-3.22/gtk-widgets.css
Instead of styling the infobar itself, style the box inside the revealer
Turns out these days infobar has a revealer packed in. By styling the revealer itself, borders are still drawn when the revealer is "closed". By styling the box inside the revealer, borders will be hidden.
Should save on adding revealers for infobars since we can just use the built-in revealed property
Handy infobar reference is either switchboard power plug or gtk3-demo
=> Style box inside the infobar revealer

gtk-3.0/gtk-widgets.css
Gets us closer to a matching selection style between views in Files:
=> Set a background on iconview selections

gtk-3.0/gtk-widgets-dark.css
Update some selectors and rules so that buttons in infobars look right in the dark stylesheet
=> Fix dark infobar buttons

gtk-3.0/gtk-widgets.css
Fixes #97 
Uses a mix (between color and background color) instead of a shade (brighten) to create the insensitive color in titlebars.
Also works better with branded titlebars:
=> Use mix instead of brighten for disabled titlebar button color

.gitignore, README.md, meson.build
Add a basic Meson build system to handle installation and update README to recommend installing with it.
This will come in handy if we move to a pre-processor and makes it so we don't need to rely on packaging to install files
=> Add Meson build system

elementary/gtk-3.0/gtk-widgets.css
We weren't sure what this was for, and it's causing weird styling in the AppCenter StripeDialog.
=> Remove overly specific style

elementary/gtk-3.0/granite-widgets.css, elementary/gtk-3.0/gtk-widgets.css
When using the error class in infobars, makes the close button white instead of dark.
Fixes #380.
Looks like this:
Old =
New =
=> Make close button icon white in error-type Infobars

elementary/gtk-3.0/granite-widgets.css, elementary/gtk-3.0/gtk-widgets.css
This makes it so the icon doesn't land in a half-pixel, making it not blur.
Looks like this:
Old =
New =
=> Unblur the icon used to show Infobar Type

elementary/gtk-3.0/gtk-widgets.css
These selectors may have needed to be this specific in an older version of the stylesheet, but I don't see why they need to be anymore. Tested this with suggested action buttons in headers in dark and light with brand colors.
=> Fix menuitem color from suggested-action buttons

elementary/gtk-3.0/gtk-widgets.css
Make background to be visible for notebook background
and don't appear for frameless notebooks.
_________________
Current situation is that background fill occurs for frameless notebooks, but doesn't happen for notebook with frame. This problem is not elementary-specific, yet i don't have installed any elementary app with tabs (those, i have, prefer isolated tabbar looking like button box, more suitable for headerbar).
There is difference showcase below, with gtk3 apps using tabs, i could arrange on desktop to keep visible.
After:
Before:
note: ugly notebook look in tabs now got fix to upstream, but it obviously should not draw background without frame too.
=> Fix notebook background

elementary/gtk-3.0/gtk-widgets.css
This translates the light style sliders over to the dark style, much like we did for scales. This makes them a lot easier to spot and higher contrast.
| Before | After |
|-----|-----|
| ![screenshot from 2018-11-20 15 03 21](https://user-images.githubusercontent.com/611168/48805751-716da380-ecd5-11e8-9f82-c8b98cbd5035.png) | ![screenshot from 2018-11-20 15 30 24](https://user-images.githubusercontent.com/611168/48806967-4b4a0280-ecd9-11e8-8505-8142dd0e0c3f.png) |
| ![screenshot from 2018-11-20 15 03 16](https://user-images.githubusercontent.com/611168/48805759-76caee00-ecd5-11e8-802f-3195f8579c6f.png) | ![screenshot from 2018-11-20 15 30 19](https://user-images.githubusercontent.com/611168/48806956-4422f480-ecd9-11e8-8196-2445f5feadb6.png) |
=> Always use light switch sliders

elementary/gtk-3.0/granite-widgets.css
Fixes #301
Seek bar slider should be zero in width and height, it's not shown, but if there's width or height the seek bar will not exactly go where you clicked.
Before:
After:
=> Update .seek-bar scale slider style.

elementary/gtk-3.0/gtk-widgets.css
Turns out that shade works okay for dark colors like blue, but looks like garbage for green. Instead, overlay white:
=> Shade switches with white overlay

elementary/gtk-3.0/gtk-widgets.css
Intended to fix #35. This is probably the least-possible code to do that, but I understand if we want to make them look a little more raised than just outlined.
=> Naive raised support for headerbar buttons

elementary/gtk-3.0/gtk-widgets.css
I have no idea why, but this gives us slightly tighter kerning :man_shrugging:
=> Changes dialog label.primary to em font sizing

elementary/gtk-3.0/gtk-widgets.css
A follow up to https://github.com/elementary/gala/pull/534. Disables transitions on checkitems so that we don't have transitions when a menu pops up.
=> Disable transitions on checkitems

elementary/gtk-3.0/gtk-widgets.css
before:
after:
I have also added 1px top margin so that it has the same height as normal tab, and in Code it also aligns nicely to stackswitcher on left.
=> Fix inline notebook being 1px smaller when only one tab is open

elementary/gtk-3.0/gtk-widgets-dark.css
Fixes #511
Insensitive buttons with `Gtk.STYLE_CLASS_SUGGESTED_ACTION` class have blue border color in dark mode.
Those buttons no longer have blue border color in dark mode.
=> Fix the border color of insensitive button with suggested class in dark mode

elementary/gtk-3.0/gtk-widgets.css
Undershoots help smooth out the edges of scrollable widgets. We opted to look at it on a widget-by-widget basis in #340, so here's the start of that for popovers.
Notice the hard edges on the user list.
Soft edges on the user list.
=> Add undershoot to popovers

elementary/gtk-3.0/gtk-widgets-dark.css
Makes the destructive-styled button when disabled have no background color in the dark stylesheet.
Fixes #364.
Looks like this:
Old =
New =
=> Remove background color from disabled Gtk.Button in dark stylesheet

elementary/gtk-3.0/gtk-widgets.css
Fixes an issue where keycaps inside list rows have white text
=> Explicitly set color inside keycaps

elementary/gtk-3.0/gtk-widgets-dark.css
Am I crazy? It's both here:
https://github.com/elementary/stylesheet/blob/d3a440867733185b6c09103be990e94be0468976/elementary/gtk-3.0/gtk-widgets-dark.css#L446-L456
and here (which this removes):
https://github.com/elementary/stylesheet/blob/d3a440867733185b6c09103be990e94be0468976/elementary/gtk-3.0/gtk-widgets-dark.css#L566-L576
=> Remove duplicated search-bar style

elementary/gtk-3.0/granite-widgets.css, elementary/plank/dock.theme
Fixes #545 
This makes the badge or urgent indicator's background color always the intended red.
EDIT: Strawberry 300 looks more like the old red.
=> Use new BadgeColor property to color Strawberry 300

data/stylesheet.appdata.xml.in, elementary/gtk-3.0/brand-dark.css, elementary/gtk-3.0/brand.css, elementary/gtk-3.0/gtk-widgets-dark.css, elementary/gtk-3.0/gtk-widgets.css
Contrast here goes from 2.8:1 to 8.8:1 in the light style and from  2.8:1 to 5.1:1 in the dark style. So oddly the effect looks less jarring but is way more contrasty
=> Improve contrast in text selections

elementary/gtk-3.0/gtk-widgets.css
Be more specific so we don't get images in switches in popovers
=> gtk-widgets: hide images from inside switches

src/_mixins-dark.scss, src/_mixins.scss, src/banana/banana-dark.scss, src/banana/banana.scss, src/blueberry/blueberry-dark.scss, src/blueberry/blueberry.scss, src/bubblegum/bubblegum-dark.scss, src/bubblegum/bubblegum.scss, src/grape/grape-dark.scss, src/grape/grape.scss, src/lime/lime-dark.scss, src/lime/lime.scss, src/mint/mint-dark.scss, src/mint/mint.scss, src/orange/orange-dark.scss, src/orange/orange.scss, src/strawberry/strawberry-dark.scss, src/strawberry/strawberry.scss
It's gonna be too much maintenance to update these color scheme files each time we add a new import, so instead:
* move mixins to /src because they're not really widgets right?
* Have mixins import widgets
=> Dry imports

src/orange/orange-dark.scss
Whoops, looks like we missed this.
=> Greenfield: correct color-scheme for orange-dark

src/_mixins.scss, src/widgets/_widgets.scss
did a little bit of YAGNI with the outset element style. This will change in future branches, but titlebars don't use the same kind of border and shadow as buttons (or other outset elements like checks). So when we add checks and radios, we can figure out what's the best way to DRY their shadows
Doesn't try to account for focus styles or linked buttons, but should cover most common button styles
=> Add button styles

src/_mixins.scss, src/widgets/_buttons.scss, src/widgets/_cards.scss, src/widgets/_entries.scss, src/widgets/_panes.scss, src/widgets/_popovers.scss, src/widgets/_scales.scss, src/widgets/_sidebars.scss, src/widgets/_switches.scss, src/widgets/_windows.scss
Adds an `em()` function that takes a size and converts it to ems. The second argument is a font-size if you have a different context and know you want a different font size to calculate from, otherwise it defaults to elementary defaults which is 9pt.
If you don't pass in a unit, it assumes `px`.
=> Greenfield: Use ems for padding

src/_mixins.scss
This looks to give us correct values when clamped.
=> Ems: Workaround GTK clamping instead of rounding up

src/widgets/_windows.scss
While we're here, use ems for padding and round the corners on all `.titlebar`, not just headerbars
=> Slim up default-decoration titlebars

src/widgets/_popovers.scss
And keycaps in modelbuttons!
As seen in Granite Demo, but there are many modelbuttons in the panel and Terminal's menu uses one too
=> Add styles for modelbuttons

src/_typography.scss
I know we might want to do more styles for views, but this at least fixes #636 just by treating views like we do labels for now.
=> Typography: Set view foreground color

src/widgets/_index.scss
Fixes #411 
It seems like Dazzle's built in styles take priority so we can't do any real styling, we can only add support for variables it expects.
=> Add support for DazzleCompletionEntry

src/widgets/_index.scss, src/widgets/_notifications.scss
I'd like to do the styles for the notification window here to make sure that these shadows are kept consistent with other window types, especially if/when we differentiate between dark and light styles. These things aren't really exposed in the public API and so far there's no reason to expect they would be
Goes with: https://github.com/elementary/notifications/pull/79
=> Add basic notification styles

src/widgets/_views.scss
viewport should only have a background when it has `.view` class so that we can remove it if we need to
=> Views: don't give viewport a bg

.github/workflows/main.yml, README.md, meson.build
=> Use `sassc` since `sass` is deprecated

src/widgets/_windows.scss
Fixes black squares under menu borders.
Since `menu decoration` is a child of `window`, it was being selected here
=> Windows: only set decoration radius of immediate child

src/_typography.scss, src/widgets/_index.scss, src/widgets/_lists.scss, src/widgets/_sidebars.scss
Copying the selection style here might end up being too light, but I wanted to try it
* Adds `selected_bg_color` and `selected_fg_color` public variables
* Re-add the padding rule for .h4 labels
* Removes the rule for `label` because this is too specific and it breaks styles such as in the datetime indicator and calendar. We should add `color` rules to containers, but probably not labels and images themselves
* Make sure that lists have a bg-color(1), unless they're in popovers. Almost always when we use a list in a popover we don't want it to have a background. If we do, we put it inside a frame with `view` class
=> Add basic List styles

src/widgets/_toolbars.scss
Fixes #587 
`.inline-toolbar` will be going away in Gtk4, so treat `.flat` as the same
=> Toolbars: Add style for flat and inline actionbars

src/_typography.scss, src/variants/banana-dark.scss, src/variants/banana.scss, src/variants/blueberry-dark.scss, src/variants/blueberry.scss, src/variants/bubblegum-dark.scss, src/variants/bubblegum.scss, src/variants/cocoa-dark.scss, src/variants/cocoa.scss, src/variants/grape-dark.scss, src/variants/grape.scss, src/variants/lime-dark.scss, src/variants/lime.scss, src/variants/mint-dark.scss, src/variants/mint.scss, src/variants/orange-dark.scss, src/variants/orange.scss, src/variants/slate-dark.scss, src/variants/slate.scss, src/variants/strawberry-dark.scss, src/variants/strawberry.scss
The previous method breaks apps who want to set their own accent color.
We also rely on a single accent color variable in apps like Calendar and Tasks to be able to override easily.
This should preserve our special calculations for contrasty accent colors while having only one easily overridden accent color variable
=> Define accent color in variant

src/_exported.scss, src/_index.scss, src/variants/banana-dark.scss, src/variants/banana.scss, src/variants/blueberry-dark.scss, src/variants/blueberry.scss, src/variants/bubblegum-dark.scss, src/variants/bubblegum.scss, src/variants/cocoa-dark.scss, src/variants/cocoa.scss, src/variants/grape-dark.scss, src/variants/grape.scss, src/variants/lime-dark.scss, src/variants/lime.scss, src/variants/mint-dark.scss, src/variants/mint.scss, src/variants/orange-dark.scss, src/variants/orange.scss, src/variants/slate-dark.scss, src/variants/slate.scss, src/variants/strawberry-dark.scss, src/variants/strawberry.scss, src/widgets/_buttons.scss, src/widgets/_index.scss
Was from my work in https://github.com/elementary/stylesheet/compare/destructive, but pulled out. Supersedes #735 I guess. Only focuses on GtkCSS variables to keep it clear what is external vs internal API.
- Creates new `_exported.scss` file with only exported GtkCSS variables. Things that Dazzle, GTK apps, and apps using foreign drawing APIs might expect. The closest thing GTK has to a theming API.
- Renames `_mixins.scss` to `_index.css` since we're using it for variable definitions, placeholder classes, mixins, and anything else that doesn't have a better home yet.
=> Move exported GtkCSS variables to their own file

src/widgets/_index.scss, src/widgets/_menus.scss, src/widgets/_popovers.scss
* Add highlights to separators
* Menu separators can only be horizontal and never get the `horizontal` class. This fixes them being unstyled
* Popover separators sometimes want 0 margin because they butt up against scrolled windows, so we only apply margin to menu separators where we know we're working with a simpler set of widgets. We use margin, not min-height/width because borders are on the outside of the box
=> Separator fixes

src/widgets/_buttons.scss
Fixes #700 
Turns out using `:not():not()` is very specific and was causing issues with working on some styles like spinbuttons
Should also fix some other cases where buttons should be raised. Check page 3 of gtk-widget-factory against Adwaita for example
=> Buttons: Redo rules around flatness

src/widgets/_buttons.scss
Fixes #496 
Fixes #589 
I just spent like 20 minutes trying to figure out why the toggle button in gtk3-widget-factory was losing the color when `:checked` and it turns out that they remove `.destructive-action` when it's toggled 😑️
=> Style destructive-action buttons

src/widgets/_buttons.scss
When a button contains both an image and a label, make sure we add column spacing
=> Button: Add spacing between images and labels

src/_typography.scss, src/widgets/_toolbars.scss, src/widgets/_windows.scss
Porting over missing title and subtitle styling, while also updating it for the new stylesheet.
Looks like this:
=> Titles & Subtitles

src/widgets/_menus.scss
These styles are for checkmenuitem and image menu items in menus, but they do fucky things to layouts in popovers like in the bluetooth menu
=> Menus: Only apply image and check styles to menu menuitem

src/_index.scss, src/widgets/_buttons.scss, src/widgets/_checkbuttons.scss, src/widgets/_levelbars.scss, src/widgets/_progressbars.scss, src/widgets/_scales.scss, src/widgets/_switches.scss
Supersedes #780 
Fixes #671 
Introduces a new bg level 0 for inputs. This is used for buttons, switch handles, sliders, checkboxes, etc
This also darkens the view color which makes apps like Files not so ugly:
You'll also notice no significant impact on the light style:
=> Add a bg level for inputs

src/widgets/_checkbuttons.scss
=> CheckButtons: Fix image color in dark radiobuttons

src/widgets/_separators.scss, src/widgets/_sidebars.scss
As seen in GraniteDemo. I don't want seps in my stacksidebar
=> Remove separators from StackSidebar

src/_typography.scss
This will probably be the best fix for https://github.com/elementary/sideload/issues/98
Otherwise we have to load stylesheets in and out or something complicated
Once this is merged we can get rid of the custom stylesheet in sideload and just set `.accent.orange` and `.accent.purple` etc
=> Typography: Allow specifying accent color

src/widgets/_lists.scss, src/widgets/_treeviews.scss, src/widgets/_views.scss
Fixes #781 
Yo dawg I heard you like to get around with a keyboard
Shows focus and selection in flowboxes, listboxes, icon views, and treeviews such as in:
* Files
* System Settings
* Music
* Videos
* And More!
Does not work for the applications menu because that is a bunch of buttons in a grid. Gross
=> Show selection and focus in Grids and Lists

src/_typography.scss, src/variants/banana-dark.scss, src/variants/banana.scss
Makes accent color transforms way less aggressive. In apps like Tasks, getting to AA with every color (yellow in light, red in dark) was requiring really aggressive transforms to where you could barely even tell what color certain ones were supposed to be (like mint).
I think it's okay to settle for A grade contrast with accent labels since they'll likely be either large bold primary text or used for icons or something other than normal body labels
=> Typography: lower contrast of accent labels

src/widgets/_sidebars.scss
I was trying to be too clever here. This messes up padding in the new Files listbox sidebar
=> Sidebar: Remove list top padding

src/widgets/_spinners.scss
Our spinner icon is designed for a discrete 12-frame spin, but we're currently smoothly animating the whole spin. This PR sets the animation-timing-function for spinners specifically to take 12 steps, also matching the new BGRT plymouth theme.
This is hard to capture in a GIF because of framerate, but here's an attempt; notice in the "after" GIF the spokes stay in the correct orientation.
Before | After
---|---
=> Spinners: spin discretely

src/widgets/_entries.scss
This prevents a resize jump when adding icons to entries such as in User Accounts when creating a new user
=> Entries: Set minimum height to accomodate icons

src/widgets/_sidebars.scss, src/widgets/_treeviews.scss
Fixes #896 
We can't use transparent backgrounds here in treeview because I guess the widgets are stacked
=> Fix editable treeview cell background color

src/widgets/_windows.scss
This is a bad hack and it's causing issues in FileChooser dialogs
=> Windows: don't set negative margin in dialogs

src/widgets/_sidebars.scss
Gets rid of multiple extra frames in file chooser dialogs
=> Sidebars: Get rid of extra frames in GtkPlacesSidebar

src/widgets/_windows.scss
This fixes the incorrect extra spacing in, for example, file chooser dialogs
requires https://github.com/elementary/granite/pull/462
=> Windows: Only apply action area double space to messagedialog

src/widgets/_windows.scss
Fixes #944 
And titlebar styles only apply to CSD
=> Windows: only round CSD dialogs

src/_exported.scss, src/widgets/_index.scss
Fixes #734 
text selections now lose color in backdrop. Gtk widget factory is probably one of the easiest ways to test this
=> Add and use unfocused selected colors

src/widgets/_buttons.scss
Fixes #866 
Added benefit of less code and matching selection styles. Even if its too pastel in the light style or we like the brighter text in the dark style, I think this is the right direction to go in code and we can adjust the selection style to be more saturated if that's what we want
=> Buttons: suggested-action extends selection

src/_exported.scss, src/_index.scss, src/widgets/_checkbuttons.scss, src/widgets/_entries.scss, src/widgets/_views.scss
Fixes #803
Make insensitive base color relative to background levels and use it in entries (and thus spinbuttons), checkbuttons, and views.
=> Further define and use insensitive base color

src/_index.scss
Supersedes #965
Fixes #822
Adjusted level 3 and 4 in the dark style so that we have the same contrast ratio between steps as we do in the light style. Ever so slightly darken titlebars, but using level4 feels really harsh in the dark style
=> Index: Adjust dark levels by contrast

src/widgets/_popovers.scss
Fixes #981 
Also make sure we set the correct horizontal margin on h4 labels in popovers such as in the keyboard indicator when you configure multiple layouts and input methods
=> Popovers: set correct margin and padding on h4

src/widgets/_popovers.scss
Fixes #955 
This kind of made some modelmenus look better, but it really breaks some menus like in Akira and some other apps
=> Popovers: Remove modelmenu hack

src/widgets/_buttons.scss
Fixes #1006
This follows the un-focused selection color as in list views. Focused items have accent color
=> Buttons: Add a background to checked flat buttons

src/_exported.scss, src/widgets/_notebooks.scss
Fixes #1024 
No need for another style class anymore. Also self-contain hdy.tabbox a bit here to fix issues with box shadow
=> Notebooks: use tab_base_color

src/widgets/_scales.scss
Fixes #1051 
It looks like outline doesn't affect switch sliders, so we have to use box-shadow here and do some funky layering to emulate it
=> Scales: Add focus styles

src/widgets/_linked.scss
Fixes an issue with the linked selectors in Calendar (and probably other places). Linked image buttons are still linked, so make sure we're specific to give them the correct border radius
=> Linked:specify image-button to override border-radius

src/widgets/_scales.scss
Makes it so you can add `accent` class and only define `accent_color` to set accents for scales
=> Scales: don't require setting accent_500 for accent

data/stylesheet.appdata.xml.in, src/widgets/_views.scss
Fixes #1067
The highlight word in IBus candidate window is redacted and unreadable.
Now the highlight word uses the accent color preferred in System Settings, so it's visible and plus provides design consistency.
I'm not familiar with the structure of this repository, so feel free to move the changes to the appropriate place.
=> Use the accent color for highlighting in IBus candidate window

src/_exported.scss
This adjustment makes the horizontal separation line a bit darker, so it can be distinguished more clearly from the background color of the dark theme. See issue #1091 and issue elementary/files#1856
=> adjust opacity of menu_separator in dark color scheme

src/gtk-3.0/widgets/_treeviews.scss, src/gtk-4.0/widgets/_treeviews.scss
Fixes #1120
The same fix with #1102 by @danrabbit works! :tada:
You can test if this works by building https://github.com/ryonakano/junk/tree/file-chooser-test-css-test as Flatpak
=> Treeview: set title font-weight as bold

src/gtk-4.0/widgets/_images.scss
Gtk4 drops the old prescriptive icon size and let's us define what icon size means in CSS with only two built-in options "Normal" and "Large". https://github.com/GNOME/gtk/blob/50e4ca8593d12b2de76e4d092d34ec7a1655ede8/gtk/gtkimage.c#L77
Adwaita's defaults are 16px and 32px, so that's what I've left here.
I imagine in future branches we might want to change this so that for example large images in buttons are 24px instead but large images in lists are 32px
Either way, `pixel_size` is still available, so this is just a convenience property and not super critical
=> GTK4/Icons: support IconSize

src/gtk-4.0/widgets/_buttons.scss, src/gtk-4.0/widgets/_headerbars.scss, src/gtk-4.0/widgets/_index.scss, src/gtk-4.0/widgets/_separators.scss, src/gtk-4.0/widgets/_windowcontrols.scss
.titlebutton isn't a thing anymore. Instead there's an element `windowcontrols` which contains all the title buttons
There's also no longer a separator in headerbar, so to maintain margins here we can add margin to the `windowcontrols` widget
=> GTK4/Headerbars: .titlebutton → windowcontrols

src/gtk-4.0/widgets/_expanders.scss
No more `arrow` element here, just `expander`
=> GTK4/Expanders: remove arrow node

src/gtk-4.0/widgets/_calendars.scss
Imitates styles from Date & Time indicator:
* Today is bold and accent colored even when not selected
* h4 headers
=> GTK4/Calendars: fix and imitate date-time indicator

src/gtk-4.0/widgets/_colorchoosers.scss
=> GTK4/ColorChoosers: remove overlay margin

src/gtk-4.0/widgets/_entries.scss
Fixes #1142 
Padding/Margin was moved to image and text inside entries instead of on the entry itself. This prevents the entry from growing to an unreasonable height with the progress element inside it.
=> GTK4/Entries: progress size and style

src/gtk-4.0/_index.scss, src/gtk-4.0/widgets/_buttons.scss, src/gtk-4.0/widgets/_images.scss, src/gtk-4.0/widgets/_index.scss, src/gtk-4.0/widgets/_spinners.scss
This is based on how Adwaita replaced `-gtk-icon-effect` which no longer exists
See for example: https://github.com/GNOME/libadwaita/search?l=SCSS&q=icon+dim
=> GTK4: Replace icon-effect with filter

src/gtk-4.0/widgets/_headerbars.scss, src/gtk-4.0/widgets/_windows.scss
There's no longer separate element names for different types of windows. Instead, a window is a window and there are different classes (makes total sense!). This branch fixes decorations for SSD and CSD dialogs, and makes some progress (but not perfect) towards `window.dialog.message` support.
We intentionally hide titles in dialogs in the GTK3 version of our stylesheet already. Since we have a Granite.Dialog/Granite.MessageDialog I'm not sure if we want to stop doing that?
=> GTK4/Windows,Headerbars: fix decorations for dialogs

src/gtk-4.0/widgets/_scales.scss
Fixes an issue where scale slides couldn't be dragged all the way to the ends:
=> GTK4/Scales: sliders to the end

src/gtk-4.0/_typography.scss, src/gtk-4.0/widgets/_popovers.scss
Fixes ##1139
Styles them the same as Granite AccelLabel, with the exception that they use a single label so each key can't be its own thing for the stock GTK accels
=> GTK4: style accelerator node

src/gtk-4.0/widgets/_popovers.scss
MenuItem doesn't exist anymore and ModelButton is no longer publicly accessible. Instead, we can use Button with `menuitem` style class.
For now I've kept some separate styling of `.menuitem` in `popover.menu` just to avoid unintended fallout, but this might be combined in later branches if we can verify it doesn't make a big difference 
* Add overrides for button styles
* Clean up duplicate separate style
* Clean up duplicate menuitem style
=> GTK4/Popovers: style button.menuitem

src/gtk-4.0/widgets/_index.scss
It looks like we get some funky aliasing when we use percentages that have the same value. Using pixels fixes this:
=> GTK4: fix checkerboard

src/gtk-4.0/widgets/_calendars.scss, src/gtk-4.0/widgets/_entries.scss
Goes with: https://github.com/elementary/granite/pull/559
Fixes a bug with calendar widgets in popovers
=> GTK4/Entries: style date-picker and time-picker

src/gtk-4.0/widgets/_windows.scss
This makes dialogs nearly identical to how they were in GTK3
=> GTK4/Windows: dialog tweaks

src/gtk-4.0/widgets/_spinbuttons.scss
Fixes #1132
* `entry` node no longer exists, style `text` instead
* `button`s are now `.image-button`, so less to override but needs active styles
=> GTK4/Spinbuttons: fix padding and active style

src/gtk-4.0/_typography.scss, src/gtk-4.0/widgets/_index.scss, src/gtk-4.0/widgets/_shortcuts.scss
There's still not toplevel selector, so we can't do anything about the headerbar style :(
* Fix window margin on Gtk.ShortcutWindow
* Remove `+` signs from Gtk.ShortcutLabel
=> GTK4: style ShortcutWindow

src/gtk-4.0/widgets/_popovers.scss
This fixes all the modelbutton styles in GTK4 Widget Factory, but only for LTR. It looks like RTL has a lot of other issues that I'd like to follow up on in future PRs
=> GTK4/Popovers: fix modelmenu styles

src/gtk-4.0/_typography.scss
* Make sure we don't style the entire label with accent color when it contains a link
* Add underline to links
=> GTK4: fix link styles

src/gtk-4.0/widgets/_windows.scss
fixes incorrect margins and border radius on SSD windows
drop `.assistant` and `.printdialog` which are now classes for `window`
=> Fix SSD windows

src/gtk-4.0/_typography.scss, src/gtk-4.0/widgets/_popovers.scss
Fixes the font weight of labels in a `title-4` container, like Granite.SwitchModelButton
=> ModelButton: fix title-4 weight

src/gtk-4.0/widgets/_sidebars.scss
While we're here fix a terminal warning and style all rows. Fixes Gtk4 Demo, Assistant, and Inspector:
=> Sidebars: right border except in paned

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/_lists.scss
We use the .title-* class in Granite now to follow Gtk4
=> Lists: fix .title-4 padding

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/_buttons.scss
We want to be very careful not to set properties on button children like labels and images because popovers will inherit those properties.
This fixes an issue where all the text inside popovers on menubuttons was incorrectly weighted
=> Button: inherited label properties

src/gtk-3.0/widgets/_menus.scss, src/gtk-4.0/widgets/_popovers.scss
Fixes #1216 
Superseded #1217 
This style applies to arrows for submenus as well as for the overflow arrows in long combobox menus, so we need to be careful about styling both.
Instead of "removing" disabled arrows, which causes issues with submenu arrows, we simply dim them
=> Menus/Popovers: dim disabled arrows, not shrink

src/gtk-4.0/widgets/_scales.scss
Fixes #1219
It looks like vertical scale marks are always on the right, even in RTL so we don't need to account for that
=> Gtk4/Scales: fix mark selector

src/gtk-4.0/widgets/_headerbars.scss, src/gtk-4.0/widgets/_images.scss
Makes my life easier to set icon sizes for buttons and menu buttons in titlebars. Especially for menubuttons since manually setting the child means no image-button class and it isn't easy to select the button since the popover is also a child. `has_frame` technically works here, but it adds `flat` which is slightly different from `image-button`.
Also in `images`, don't require the `large-icons` class to be directly on an image, because it's useful to set it on a container widget like a button
Vala before:
```vala
var updates_button = new Gtk.Button.from_icon_name ("software-update-available");
((Gtk.Image) updates_button.child).pixel_size = 24;
var menu_button = new Gtk.MenuButton () {
child = new Gtk.Image.from_icon_name ("open-menu") {
pixel_size = 24
},
has_frame = false
};
```
Vala …
=> HeaderBars: set large-icons size to 24px

src/gtk-4.0/widgets/_settingspages.scss
* Make titles bold, more modern. Super thin title text is kinda out of style
* Match switch size to title text height
* Adjust icon padding for canvas white space (see with square icon at the bottom)
* Make description text slightly smaller and lighter
Demonstrating that the edges of tile icons line up with the frame now:
=> SimpleSettingsPage: adjust header layout and text size

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/_popovers.scss
Fixes lack of padding in completion entry menus
=> Gtk4/Popovers: style completion-entry

src/gtk-4.0/widgets/_checkbuttons.scss
Fixes an issue where image children of checkbuttons have extra margins. Normal case is unchanged
The extra padding between the check and entry here is now an issue with the plug since it's adding its own 6px margin to try to make up for the previously missing margin in the stylesheet
=> CheckButtons: set margin on check/radio element

src/gtk-4.0/widgets/_buttons.scss
See https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3390
I guess this class needs to be used in some other places, but this is bare minimum for https://github.com/elementary/calculator/pull/242
=> GTK4: Support `.keyboard-activating` class for buttons

src/gtk-4.0/widgets/_headerbars.scss, src/gtk-4.0/widgets/_windows.scss
=> Windows: Remove Gtk3-isms and fix Mutter 44

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/adw/ToolbarView.scss
I've used this twice now in Switchboard and in Music. Better replacement for `.inline-toolbar`
=> ToolbarView: add bottom-bar styles

src/gtk-3.0/meson.build, src/gtk-4.0/meson.build
it is defined since years but was never added to builds, somehow
=> Add Latte - the Lost Stylesheet, to the built sheets

src/gtk-4.0/widgets/_treeviews.scss
Fixes #1273
This fixes sort indicators are not being shown in TreeViews.
Affected  https://github.com/elementary/monitor/pull/443
Special thanks to @Marukesu for diagnostics.
=> Show sort-indicator in treeviews

src/gtk-4.0/widgets/_badges.scss, src/gtk-4.0/widgets/_buttons.scss, src/gtk-4.0/widgets/_checkbuttons.scss, src/gtk-4.0/widgets/_columnviews.scss, src/gtk-4.0/widgets/_lists.scss, src/gtk-4.0/widgets/_scales.scss, src/gtk-4.0/widgets/_switches.scss, src/gtk-4.0/widgets/_treeviews.scss, src/gtk-4.0/widgets/_views.scss
Fixes #1055
Fixes #1069
Changes use of `focus` to `focus-visible.
Widgets no longer get focus styles when clicked or on app startup, just when keyboard navigation is being used. And focus styles disappear after a little bit
=> focus → focus-visible
