gtk-3.0/apps.css, gtk-3.0/granite-widgets.css
=> move cards from apps to granite-widgets

gtk-3.0/granite-widgets.css
Fixes #5 by adding a class that sets rounded bottom corners on windows
=> add rounded class for windows

gtk-3.0/granite-widgets.css
=> don't hardcode background colors in card

gtk-3.0/apps.css
=> don't hardcode round apps

gtk-3.0/gtk-widgets.css
=> scrollbar adjustments to fix webkitgtk issues

gtk-3.0/gtk-widgets.css
just a bitesized fix to make a feature in AppCenter happy
=> make sure textviews in rows are transparent

gtk-3.0/gtk-widgets.css
=> fix flat button focus style in a selected row

gtk-3.0/gtk-widgets.css
=> Fix SSD active state

gtk-3.0/apps.css
This fixes an issue where we accidentally added box shadow on the panel
=> fix an oops we made on the greeter panel

gtk-3.0/gtk-widgets.css
=> attempt to fix scrollbar min sizes

gtk-3.0/apps.css
This is for after [Corentin's Branch](https://code.launchpad.net/~tintou/pantheon-photos/grid-css) is merged
=> remove checkerboard pattern

gtk-3.0/apps.css
Seems like the embedded stylesheet doesn't work and removing this CSS breaks photos
=> Revert Photos CSS removal

gtk-3.0/gtk-widgets-dark.css, gtk-3.0/gtk-widgets.css
=> Fixed switch active\inactive state background, fixed selection in entry and textview

gtk-3.0/gtk-widgets.css
Revert changes made in #77 to the selector that targets 3.18
=> Revert change that breaks switch active states in 3.18

gtk-3.0/gtk-widgets.css
=> fix background of some HeaderBar buttons

gtk-3.22/apps.css, gtk-3.22/granite-widgets.css, gtk-3.22/gtk-widgets-dark.css, gtk-3.22/gtk-widgets.css
=> Rename icon-shadow to -gtk-icon-shadow

gtk-3.22/gtk-widgets-dark.css, gtk-3.22/gtk-widgets.css
The `:insensitive` pseudo class is now `:disabled`. Fixes a bunch of deprecation warnings
=> :insensitive is now :disabled

gtk-3.22/gtk-widgets.css
=> Fix inline actionbar selector

gtk-3.22/gtk-widgets.css
Fixes menu separators by changing padding to margin
removes deprecated values
draw seps with magic gradients to workaround gtk align fill
=> Fix separators

gtk-3.22/gtk-widgets.css
Make sure we're selecting with `label`
=> Clean up label selectors

gtk-3.22/gtk-widgets.css
=> Give Radio and Check labels a margin

gtk-3.22/gtk-widgets.css
=> Fix default decoration height

gtk-3.22/gtk-widgets.css
You can see this in gtk3-widget-factory
=> Fix linked comboboxes

gtk-3.22/gtk-widgets.css
* Remove 3.18 selectors
* Use min-height/width instead of vendor prefix properties
* Fix margins
=> Clean up levelbar

gtk-3.22/gtk-widgets.css
* Remove old selectors from 3.18
* Replace tab overlap with negative margin
* Fix border for unchecked tabs
* Fix backdrop for checked tabs
=> Clean up notebooks

gtk-3.22/gtk-widgets.css
* remove selectors from 3.18
* Fix regression in entry image color
* Make sure we respect backdrop states
* Add a hover state for secondary icon
=> Fix entry image colors

gtk-3.22/gtk-widgets.css
Pictured below, from top to bottom:
3.18
With this branch
Without this branch
=> Headerbar padding

gtk-3.22/gtk-widgets.css
* Remove selectors from 3.18
* Fix size of horizontal scrollbars
=> clean up scrollbars

gtk-3.22/gtk-widgets.css
=> clean up combobox selectors

gtk-3.22/gtk-widgets.css
* Remove selectors from 3.18
* Fix entry progressbars
=> clean up progressbars

gtk-3.22/gtk-widgets.css
* Remove 3.18 selectors
* Save some lines with `:not` selector
=> rewrite colorchooser

gtk-3.22/gtk-widgets.css
`GtkImage` is no longer a valid selector. Use `image`
=> Replace GtkImage with image

gtk-3.22/gtk-widgets.css
* Remove selectors from 3.18
* Fix scale marks not showing (see keyboard plug or gtk3-widget factory)
=> Clean up scales and fix marks

gtk-3.22/gtk-widgets.css
* remove selectors for 3.18
* Only re-style image buttons
* Fix over-specific selectors
* Fix extra borders on actionbars
=> refine inline-toolbar selectors, fix bugs

gtk-3.22/gtk-widgets.css
* Remove deprecated vendor prefixes
* Remove 3.18 selectors
* Add selectors for >=3.20
=> fix infobar selectors

gtk-3.22/gtk-widgets.css
Seems to be no effect :man_shrugging:
=> Remove deprecated properties

gtk-3.22/gtk-widgets.css
* Remove selectors for 3.18
* Replace vendor prefix properties with native properties
=> update switch selectors

gtk-3.22/gtk-widgets.css
* fix selector for actionbar image buttons
* Make sure we clear button style completely for inline-toolbar image buttons
* Place :active after :focus so that it's actually used
=> fix a couple of image button selectors

gtk-3.22/gtk-widgets.css
=> Add attention class

gtk-3.22/gtk-widgets.css
De-duplicate the check, radio, and switch selectors
=> combine check, radio, and switch selectors

gtk-3.22/gtk-widgets.css
This exact thing is present just a couple lines down
=> Remove duplicate selector

gtk-3.22/gtk-widgets.css
=> Add a style for .keycap

gtk-3.22/gtk-widgets-dark.css
This is already covered by the variables in gtk-widgets.css
=> Remove redundant dark titlebar style

gtk-3.0/gtk-widgets.css, gtk-3.22/gtk-widgets.css
Tested in all standard eOS apps. Fixes #3 
Images from Gtk Widget Factory:
=> Improved combobox obviousness

README.md
=> Add instructions to enable the inspector

gtk-3.0/apps.css, gtk-3.0/granite-widgets-dark.css, gtk-3.0/granite-widgets.css, gtk-3.22/apps.css, gtk-3.22/granite-widgets-dark.css, gtk-3.22/granite-widgets.css
Updates the Free Software Foundation address in license headers
=> Update FSF address

gtk-3.22/granite-widgets.css, gtk-3.22/gtk-dark.css, gtk-3.22/gtk.css
First commit towards fixing #189 
* Replace values in gtk.CSS with colors from the palette
* Remove dead color constants
=> Replace colors in gtk.css with palette colors

gtk-3.22/apps.css, gtk-3.22/gtk.css
Silver 300 is just a little too dark
**Before:**
**After:**
=> Brighter titlebar

gtk-3.22/gtk-widgets.css
=> Fixes nested linked entry in AppCenter

gtk-3.22/gtk-widgets-dark.css, gtk-3.22/gtk-widgets.css
=> Ensure that colored labels have higher contrast

gtk-3.0/granite-widgets.css, gtk-3.22/granite-widgets.css
This adds the fake Vte style we use in the installer and in error dialogs to embed Terminal output in other UIs
=> Add fake terminal style

gtk-3.22/granite-widgets.css
=> Add a fancy temperature scale style

gtk-3.22/granite-widgets.css
Because it's more accurate for night light than a blue/orange gradient
=> Add a warmth scale

gtk-3.22/gtk-widgets.css
Make sure we style the link element inside labels and not just link buttons
=> Style the link element

gtk-3.22/gtk-widgets.css
=> Make the emoji picker look nicer

gtk-3.22/granite-widgets-dark.css, gtk-3.22/gtk-widgets-dark.css, gtk-3.22/gtk-widgets.css
=> Make dark scales all sexy

gtk-3.22/gtk-widgets.css
Makes the font size on keycaps smaller so they look better inline with other text
=> Make font size on keycaps smaller

gtk-3.22/gtk-widgets.css
Assume that developers will do the right thing
=> Don't force entry icons to be symbolic

gtk-3.22/apps.css
Fixes https://github.com/elementary/mail/issues/195
These other selectors no longer work in latest Gtk
=> Update app CSS for mail

gtk-3.22/gtk-widgets.css
=> Fix actionbar and treeview selectors

gtk-3.22/gtk-widgets.css
* Fix some duplication with menu seps
* Fixes a regression with menu seps in sidebars
=> Make separator selectors smarter

gtk-3.22/gtk-widgets.css
=> Fix entry icon color in branded titlebars

gtk-3.22/gtk-widgets.css
AppChooser is not longer a valid selector
Update selector for dialog searchbars
=> Update searchbar selectors

gtk-3.22/gtk.css
=> Add Cocoa to color constants

gtk-3.22/gtk-dark.css
Didn't realize this was a separate list of constants.
=> Add Cocoa to dark styles

gtk-3.22/gtk-widgets.css
Also fixes an issue with a background behind discrete levelbars and make vertical levelbars flatter
=> Match empty levelbar block style to progressbar

gtk-3.22/granite-widgets.css
Fixes #310. Colors were picked to be from the palette, but similar to those at https://github.com/pop-os/gtk-theme
=> Partition styles

gtk-3.22/gtk-widgets.css
=> Add icons to infobars

gtk-3.22/gtk-dark.css, gtk-3.22/gtk.css
Fixes #266 
Makes the insensitive color closer to the background color so that it's clearer when something is insensitive.
=> Increase contrast between sensitive and insensitive color

gtk-3.22/gtk-dark.css, gtk-3.22/gtk-widgets.css, gtk-3.22/gtk.css
=> Fix compatibility with some GNOME apps

gtk-3.22/gtk-widgets.css
=> Fix double titlebar/headerbar border in some GNOME apps

gtk-3.22/gtk-widgets.css
Fixes https://github.com/elementary/gala/issues/178
=> Update to latest selectors for decoration

gtk-3.22/granite-widgets.css
=> Make storagebar look better in dark stylesheet

gtk-3.22/apps.css, gtk-3.22/gtk-widgets.css
Fixes #331 
Also fixes a background gradient inconsistency with entries
=> Fix linked spinbuttons

gtk-3.0/apps.css
To be merged after https://github.com/elementary/switchboard-plug-pantheon-shell/pull/130
=> Remove CSS for Desktop settings hotcorner

gtk-3.0/gtk-dark.css, gtk-3.0/gtk-widgets.css, gtk-3.0/gtk.css
=> Add inline tabbar style

gtk-3.0/gtk-widgets-dark.css, gtk-3.0/gtk-widgets.css
Makes it much clearer when checkboxes or radios are disabled as opposed to just unchecked
=> Redo style for checks and radios

elementary/gtk-3.0/brand-dark.css, elementary/gtk-3.0/brand.css, elementary/gtk-3.0/gtk-dark.css, elementary/gtk-3.0/gtk.css
Another small split out from #376. This makes it more clear what are supported brand modifications, plus makes color variants even easier. :wink:
=> Split out brand files

elementary/gtk-3.0/gtk-widgets.css
=> Special case flat destructive action buttons

elementary/gtk-3.0/gtk-widgets.css
=> Don't change text color for disabled suggested action

elementary/gtk-3.0/gtk-widgets.css
Turns out this is a Gtk style class constant
=> Add class for accelerator

elementary/gtk-3.0/granite-widgets.css
=> Fix darkened backdrop modeswitch

elementary/gtk-3.0/gtk-widgets.css
=> Increase contrast of warning class in entries

elementary/gtk-3.0/gtk-widgets.css
=> Add styles for link pseudo classes

elementary/gtk-3.0/gtk-widgets.css
Like #262 but for scales. i.e. so we can do stuff like this:
=> Add accent support to scales

elementary/gtk-3.0/gtk-widgets-dark.css
=> More visible focus for dark entries

elementary/gtk-3.0/gtk-widgets.css
=> Fix linked widgets in RTL

elementary/gtk-3.0/gtk-widgets-dark.css
=> Don't set border or shadow on dark infobar close buttons

elementary/gtk-3.0/granite-widgets.css
=> Invert sidebar badge colors

elementary/gtk-3.0/gtk-widgets.css
=> Style destructive-action buttons in actionbars

elementary/gtk-3.0/gtk-widgets.css
=> Add support for progressbar.osd

elementary/gtk-3.0/gtk-widgets-dark.css
Attempting to fix #484 
| Before | After |
|---|---|
| ![Screenshot von 2019-05-10 15 47 50@2x](https://user-images.githubusercontent.com/43932053/57532292-a204d080-733b-11e9-9606-af98d3f4f8b3.png) | ![Screenshot von 2019-05-10 15 47 49@2x](https://user-images.githubusercontent.com/43932053/57532303-a92bde80-733b-11e9-9ebb-3c17d4e8294e.png) |
=> Increase Radio/CheckButton contrast when using dark style

elementary/gtk-3.0/gtk-widgets.css
=> Fix popover submenu arrow styles

elementary/gtk-3.0/gtk-widgets-dark.css, elementary/gtk-3.0/gtk-widgets.css
=> Fix the color of insensitive buttons

elementary/gtk-3.0/granite-widgets.css, elementary/gtk-3.0/gtk-widgets.css
And let it work outside of just Gtk.Dialog
=> Move primary label to granite-widgets

elementary/gtk-3.0/gtk-widgets-dark.css, elementary/gtk-3.0/gtk-widgets.css
=> Style keycaps in menus

elementary/gtk-3.0/gtk-widgets.css
Make sure we set opacity so buttons don't look enabled
=> Fix color for disabled flat buttons in list rows

elementary/gtk-3.0/gtk-widgets.css
This causes issues with insensitive flat buttons in list rows
=> Remove disabled text and icon shadow

elementary/gtk-3.0/granite-widgets.css
Merge after a Files release with https://github.com/elementary/files/pull/1035
=> Remove styles for Files' DiskRenderer

elementary/gtk-3.0/gtk-widgets.css
=> Add a style for separator.wide

README.md
=> Fix GTK references in README

elementary/gtk-3.0/gtk-widgets.css
Doesn't really fix the problem, but it is slightly better
=> Only apply border to SSD decoration

elementary/gtk-3.0/gtk-widgets.css
Fixes #553. Hat-tip to @jtrees. :smile:
=> Fix sidebar inline-toolbar icon style

data/stylesheet.appdata.xml.in, elementary/gtk-3.0/gtk-widgets.css
=> Add .small-label style class

data/stylesheet.appdata.xml.in, elementary/gtk-3.0/gtk-widgets-dark.css, elementary/gtk-3.0/gtk-widgets.css
=> Add border and background to selected image radios

data/stylesheet.appdata.xml.in, elementary/gtk-3.0/gtk-widgets.css
=> Fix dialog label valign

data/stylesheet.appdata.xml.in, meson.build
Tiny release, but it would be good to get that alignment fix out
=> Release 5.4.2

data/stylesheet.appdata.xml.in, elementary/gtk-3.0/gtk-widgets.css
Changes the minimum size of the continuous levelbar block so that we get more accurate levels
=> More accurate continuous levelbar

src/widgets/_mixins-dark.scss, src/widgets/_mixins.scss, src/widgets/_widgets.scss
This adds a neato little window shadow mixin helper and uses it for `window` elements
=> Add window shadows

src/widgets/_mixins-dark.scss, src/widgets/_mixins.scss, src/widgets/_widgets.scss
* Added a level3 shadow for dialogs and moved the window shadow to level4
* Redo of level2 to match the shadow we use currently in popovers because it's way nicer
* Rounded corners on windows and dialogs
=> Add dialog decorations and adjust shadow mixin

src/_mixins-dark.scss, src/_mixins.scss, src/widgets/_widgets.scss
The view mixin needs to be `background-color` because that overrides `background-clip` for some reason
=> Add popover styles

src/_mixins.scss, src/widgets/_widgets.scss
Includes a lot of the same changes to mixins as #620 
Styles the basic sidebar as seen in Granite Demo. Not intended to do all the styling required for Files (for example)
=> Add stacksidebar style

src/_mixins.scss, src/widgets/_widgets.scss
I changed the background color mixin to a function so that we could use the values with `mix`
I also tweaked the dark titlebar colors a little bit since it felt really dark after adding the entry
=> Add entry styles

src/banana/banana-dark.scss, src/blueberry/blueberry-dark.scss, src/bubblegum/bubblegum-dark.scss, src/grape/grape-dark.scss, src/lime/lime-dark.scss, src/mint/mint-dark.scss, src/orange/orange-dark.scss, src/strawberry/strawberry-dark.scss, src/widgets/_entries.scss, src/widgets/_index.scss
I dunno what kind of drugs I must have been on when I did these dark color things, but anyways:
=> Add color classes and gtk-icon-palette

src/_mixins.scss, src/_typography.scss, src/widgets/_buttons.scss, src/widgets/_entries.scss, src/widgets/_index.scss
=> Explicitly set fg_color for entries and labels

src/_mixins.scss, src/_typography.scss, src/widgets/_buttons.scss, src/widgets/_index.scss, src/widgets/_switches.scss, src/widgets/_windows.scss
=> Styles for switches

src/widgets/_checkbuttons.scss, src/widgets/_index.scss
Gonna come back to image check/radio buttons in another branch
=> Add styles for checks and radios

src/widgets/_checkbuttons.scss
=> Add styles for color buttons

src/widgets/_switches.scss
=> Fix dark checked switch

src/meson.build, src/variants/cocoa-dark.scss, src/variants/cocoa.scss, src/variants/slate-dark.scss, src/variants/slate.scss
=> Add Slate and Cocoa

src/widgets/_cards.scss
As seen on the greeter and in appearance settings
Fixes #640
=> Support rounded cards

src/widgets/_index.scss, src/widgets/_menus.scss, src/widgets/_popovers.scss
* DRY some popover and menu styles
* Fix checks, radios, and images in menus
* Workaround extra margin in ModelMenu
=> Add menu styles

src/_mixins.scss, src/widgets/_index.scss, src/widgets/_levelbars.scss, src/widgets/_progressbars.scss
Fixes #416 
Fixes #633 
This is gonna break wherever we use levelbars because we've been doing things wrong and dumb
=> Add support for levelbars

src/_animate.scss, src/widgets/_buttons.scss, src/widgets/_cards.scss, src/widgets/_checkbuttons.scss, src/widgets/_entries.scss, src/widgets/_levelbars.scss, src/widgets/_scrollbars.scss, src/widgets/_switches.scss
=> Animate: Use transition times and easing from Material

src/_mixins.scss, src/widgets/_buttons.scss, src/widgets/_cards.scss, src/widgets/_checkbuttons.scss, src/widgets/_entries.scss, src/widgets/_levelbars.scss, src/widgets/_menus.scss, src/widgets/_notebooks.scss, src/widgets/_panes.scss, src/widgets/_progressbars.scss, src/widgets/_scales.scss, src/widgets/_sidebars.scss, src/widgets/_switches.scss, src/widgets/_windows.scss
Makes it easier to read imho, and more intentional about using literal black or literal white.
=> Explicit black/white

src/widgets/_index.scss, src/widgets/_toolbars.scss
I'm thinking we're gonna have styles like toolbars and actionbars that are gonna be pretty much the same (like checks and radios), so a single toolbars file probably makes sense
=> Add a background to actionbar and .search-bar

src/widgets/_checkbuttons.scss
I cannot for the life of me get borders to work properly for some reason, but this at least colors the images
=> CheckButtons: Color checked radio button images

src/widgets/_buttons.scss
=> Add styles for suggested actions

src/widgets/_cards.scss, src/widgets/_index.scss
Not necessarily always used with cards, but mostly. Not sure if there's a better place for this
=> Add checkerboard background class

src/widgets/_index.scss
Used for help buttons and in my app Palette. :)
=> Add .circular class

src/widgets/_buttons.scss
Fixes #34
Fixes #35 
Fixes #668
draws borders on linked image buttons
=> Button: Support .raised and linked image buttons

debian/control
=> Update debian packaging for sassc

src/widgets/_index.scss
Adds in the Avatar class.
Fixes #487 too.
=> Add Avatar class

src/widgets/_windows.scss
Can be tested with https://github.com/elementary/switchboard/pull/161
=> Add support for Hdy.Window

src/widgets/_sidebars.scss
Lots more to do here eventually with hover and padding, but this at least sets the right background color.
=> Color source-list like sidebars

src/_mixins.scss
Make sure dark window borders don't look blurry over bright backgrounds
=> Mixins: Darken toplevel border for dark style

src/widgets/_index.scss
Expected by 3rd party apps like Epiphany and LibDazzle
=> Export theme_selected_bg/fg_color

src/_exported.scss
Supersedes #714
Provides many of the colors expected in #734
=> Extend exported colors

src/widgets/_notebooks.scss
As seen when you pin a tab in Epiphany
=> Notebook: set a minimum size

src/_typography.scss
Trying out something a little more modern typography-wise. I really like it, but we'll want to make sure it feels nice.
=> Typography: Bold h1 headings

src/_typography.scss
Also adds underline on hover. See Onboarding or the About plug for some examples.
=> Typography: Color links with accent color

src/widgets/_index.scss, src/widgets/_infobars.scss
=> Style infobars

src/_typography.scss, src/widgets/_menus.scss
as in the shortcut overlay
Ideally, shouldn't change menus
=> Typography: Add keycap style

src/widgets/_panes.scss
Fixes the weird extra gap after panes. Looks like maybe a rounding error
Also may address #573 maybe?
=> Panes: fix extra margin

src/widgets/_checkbuttons.scss
Bring back that nice background color
=> RadioButton: add accent background

src/widgets/_sidebars.scss
Adds some rules for treeview sidebars like in Files
=> Style treeview sidebars

src/widgets/_index.scss, src/widgets/_menubars.scss
This is mostly relevant to fix spacing in the panel
=> Style menubars

src/widgets/_sidebars.scss
Fixes #770 
as much as greenfield is responsible for. For the rest of the fix: https://github.com/elementary/applications-menu/pull/404
=> Sidebars: remove background in popovers

src/widgets/_windows.scss
=> Windows: Add messagedialog

src/widgets/_windows.scss
=> Window: Style assistant node

src/widgets/_popovers.scss
Fixes https://github.com/elementary/wingpanel-indicator-network/issues/165
=> Popovers: Style menuitem children

src/widgets/_windows.scss
As in https://github.com/elementary/tasks/pull/128
=> Windows: fix shadow on .unified.titlebar.flat:backdrop

src/widgets/_views.scss
=> Views: Round .terminal

src/widgets/_windows.scss
Should fix border radius for Hdy.Windows
=> Windows: Fix Hdy.Window for 0.90.0

src/widgets/_toolbars.scss
=> Toolbars: Style flat actionbars and their buttons

src/widgets/_colorchoosers.scss, src/widgets/_index.scss
=> Style color choosers

src/widgets/_windows.scss
=> Style printdialog windows

src/widgets/_buttons.scss, src/widgets/_toolbars.scss
=> Buttons: darken background for dark checked buttons

src/widgets/_toolbars.scss
Fixes #811 
Fixes #182 
As seen in Photos and Dconf editor
=> Toolbars: Style non-flat actionbars

src/widgets/_index.scss, src/widgets/_treeviews.scss
=> Add treeview header styles

README.md, src/widgets/_windows.scss
Fixes #804 and improves the readme a little bit.
And for your viewing pleasure:
=> Dialog gets resized on focus/unfocus

src/widgets/_index.scss, src/widgets/_windows.scss
Some leftovers from when we first started the stylesheet and hadn't organized anything yet
=> Move window styles from index

src/widgets/_index.scss, src/widgets/_separators.scss
=> Add Separator styles

src/_index.scss, src/widgets/_buttons.scss, src/widgets/_checkbuttons.scss, src/widgets/_entries.scss, src/widgets/_levelbars.scss, src/widgets/_progressbars.scss, src/widgets/_scales.scss, src/widgets/_switches.scss
More consistent border color, especially in dark theme:
=> Move border color to index

src/widgets/_switches.scss
=> Switches: Add style for :checked:disabled

src/widgets/_panes.scss
=> Fix panes with large text and support vertical

src/widgets/_avatars.scss, src/widgets/_index.scss
=> Add styles for Hdy.Avatar

src/widgets/_avatars.scss
=> Avatars: Don't draw background, neutral border with images

src/_exported.scss, src/_typography.scss, src/variants/banana-dark.scss, src/variants/banana.scss, src/variants/blueberry-dark.scss, src/variants/blueberry.scss, src/variants/bubblegum-dark.scss, src/variants/bubblegum.scss, src/variants/cocoa-dark.scss, src/variants/cocoa.scss, src/variants/grape-dark.scss, src/variants/grape.scss, src/variants/lime-dark.scss, src/variants/lime.scss, src/variants/mint-dark.scss, src/variants/mint.scss, src/variants/orange-dark.scss, src/variants/orange.scss, src/variants/slate-dark.scss, src/variants/slate.scss, src/variants/strawberry-dark.scss, src/variants/strawberry.scss, src/widgets/_checkbuttons.scss, src/widgets/_progressbars.scss, src/widgets/_switches.scss
There's some serious fuckery afoot that breaks brand colors pretty bad
This should fix app set brand colors for checkboxes, selections, progressbars, etc
=> Fix Brand Colors

src/widgets/_buttons.scss
=> Buttons: Support button.color

src/widgets/_notebooks.scss
=> Notebooks: Support all positions

src/_exported.scss, src/_index.scss, src/_typography.scss, src/widgets/_buttons.scss, src/widgets/_checkbuttons.scss, src/widgets/_entries.scss, src/widgets/_menus.scss
=> Introduce and use insensitive-fg-color

src/widgets/_entries.scss
For Tasks. Probably not the most optimal flat entry style ever, but gets the ball rolling
=> Support flat entry styles

src/widgets/_windows.scss
Fixes some busted styles: GtkAssistant, background in Tasks, probably more
=> Windows: Style .background

src/widgets/_checkbuttons.scss
Make sure we're being consistent and getting great contrast
=> CheckButtons: use selected colors for image buttons

src/widgets/_toasts.scss
=> Toasts: Support GNOME apps

src/widgets/_windows.scss
I don't really know what this is, but it's in the old stylesheet. Maybe it'll help :shrug:
=> Windows: add .gtkstyle-fallback

src/widgets/_buttons.scss
=> Fix issues with linked image-button

src/widgets/_infobars.scss
Fixes #389 
Fixes #838 
As seen in Mail image loading and Files connect server dialog
=> Infobars: Support framed infobars

src/widgets/_toolbars.scss
Fixes #836 
We also use border color here to get consistent borders and darker borders in the dark theme
=> Toolbars: style actionbar.flat:backdrop

src/widgets/_lists.scss
=> Lists: Support HdyList

src/widgets/_windows.scss
Fixes #281 
This is gonna break a bunch of stuff, but might as well get it over with.
Goes with https://github.com/elementary/granite/pull/374
=> Windows: Handle dialog action area margin

src/widgets/_buttons.scss
Not exactly the fancy shaped buttons, but works with dark/light and will work with colors etc
=> Buttons: Add back button support

src/widgets/_calendars.scss, src/widgets/_index.scss
This widget sucks and there's not much we can actually do here
=> Style Gtk.Calendar

src/widgets/_menus.scss
=> Menus: Fix insensitive and support destructive action

src/widgets/_menus.scss
Fixes letter spacing in menus in empty folders in Files
=> Menus: reset letter spacing

src/_typography.scss
=> Typography: add small-label

src/widgets/_notifications.scss, src/widgets/_progressbars.scss
=> Progressbars: support flat style

src/widgets/_buttons.scss, src/widgets/_checkbuttons.scss, src/widgets/_entries.scss, src/widgets/_index.scss, src/widgets/_linked.scss, src/widgets/_spinbuttons.scss
Fixes #730 
Introduces focus style for:
* Buttons
* Checkboxes
* Radios
* Entries
* Spinbuttons
Does not include
* Scales
* Switches
* Modelbuttons
* probably lots of other stuff
=> Focus styles

src/_index.scss, src/widgets/_entries.scss, src/widgets/_images.scss, src/widgets/_index.scss
=> Add images file

src/_exported.scss
Fixes #798 
Used with https://github.com/elementary/appcenter/pull/1464
=> Exported: add insensitive_bg_color

src/widgets/_buttons.scss
=> Buttons: Remove link padding

src/widgets/_views.scss
In the installer this class is added to the scrolled window, not just the view
=> Views: Fix terminal class for Installer

src/widgets/_menus.scss
This doesn't fix the issue with small menus in the applications menu, but it does fix showing the scroll arrows
=> Menus: Fix menu scroll arrows

src/widgets/_badges.scss
As used in Mail's conversation list
=> Badges: support .flat

src/widgets/_levelbars.scss
Fixes #883 
This vastly simplifies the CSS used in Files new listbox sidebar: https://github.com/elementary/files/pull/1549
=> Levelbars: support .flat

src/widgets/_windows.scss
Fixes #696 
I guess Gtk really hates this being 1.00000whatever12199110000000px
=> Windows: Fix double box shadow at edges

src/widgets/_sidebars.scss
=> Sidebars: Add styles for GtkAssistant

src/widgets/_buttons.scss, src/widgets/_entries.scss, src/widgets/_linked.scss, src/widgets/_toolbars.scss, src/widgets/_windows.scss
Fixes:
* Double titlebar shadow
* Linked buttons in preferences
* Bottom bar in preferences window
* No box shadow on URL entry thingy
The back/forward buttons I don't think I can fix. They're using .linked styles so we need to remove that upstream.
You can test by building Epiphany git from Flatpak with this modified manifest:
`flatpak-builder --user --install --force-clean build org.gnome.Epiphany.json`
```
{
"app-id" : "org.gnome.Epiphany.Devel",
"runtime" : "org.gnome.Platform",
"runtime-version" : "3.38",
"sdk" : "org.gnome.Sdk",
"command" : "epiphany",
"tags" : [
"nightly"
],
"desktop-file-name-suffix" : " (Epiphany Technology Preview)",
"finish-args" : [
"--device=dri",
"--filesystem=/run/.heim_org.h5l.kcm-socket",
"--filesystem=xdg-download",
"--share=ipc",
"--share=network", …
```
=> Epiphany Fixes

src/widgets/_linked.scss
=> Linked: Fix spinbuttons

src/widgets/_progressbars.scss
=> Progressbars: Remove animation from .flat

src/widgets/_index.scss, src/widgets/_viewswitcher.scss
This adds some starting styling for the widget HdyViewSwitcher.
Fixes #917
=> Add: HdyViewSwitcher styling

src/widgets/_buttons.scss
Restrict transition for only backgroud property of button (for active state). #903
=> set transition for only background

src/_typography.scss, src/widgets/_index.scss
I forgot to uncomment some code and somebody approved it anyways!!
Also, maybe we want to do this for all backdrop images instead of #899 ?
=> Make backdrop accent images text colored

src/widgets/_buttons.scss, src/widgets/_index.scss
=> Scope icon dimming to buttons

src/_exported.scss, src/widgets/_views.scss
=> Add and use insensitive_base_color

src/_exported.scss
Another towards #734 
We're not really doing anything with any of these right now, but at least they will return something and not transparent
=> Exports: Add misc unused variables

src/widgets/_sidebars.scss
Fixes an issue in Tasks, after https://github.com/elementary/tasks/pull/202 is merged
I know its a hella specific selector, but I couldn't get it to stick otherwise. Maybe too much nesting in `windows`
=> Sidebars: color flat headerbars inside sidebars

src/_index.scss
Fixes #978 
Ensure we get the same contrast for the dark style by making it much more opaque
=> Index: Use alpha for insensitive base color

src/widgets/_notebooks.scss
This theoretically supports Hdy.Tabbox, but there's some funky rendering issues that I don't think are my fault
=> Support Hdy.Tabbox

src/widgets/_emojipicker.scss
=> EmojiPickers: Add margin for entry focus

src/_animate.scss, src/widgets/_spinners.scss
=> Spinners: Move entry animation here and update

src/widgets/_notebooks.scss
=> Notebook: style overflow arrows

src/widgets/_notebooks.scss
=> Extend .flat class to Hdy.Tab indicator buttons

src/widgets/_linked.scss
=> Linked: remove extra horizontal margin

src/widgets/_buttons.scss
Fixes the buttons in Epiphany, dconf etc
=> Buttons: reset button radius for raised/linked/etc

src/widgets/_headerbars.scss, src/widgets/_index.scss, src/widgets/_windows.scss
The windows file is pretty hard to follow and titlebar styles are pretty complicated on their own. Breaking into their own files to hopefully be able to understand them better
=> Add _headerbars.scss

src/_animate.scss, src/widgets/_buttons.scss, src/widgets/_cards.scss, src/widgets/_checkbuttons.scss, src/widgets/_entries.scss, src/widgets/_expanders.scss, src/widgets/_levelbars.scss, src/widgets/_notebooks.scss, src/widgets/_scrollbars.scss, src/widgets/_switches.scss
To match https://github.com/elementary/granite/pull/498
=> Rename 'element' transition to 'in-place'; use in notebooks

src/widgets/_infobars.scss
=> Infobars: fix dark button borders

src/widgets/_windows.scss
=> Windows: Add 1px stroke to tiled windows

src/widgets/_headerbars.scss, src/widgets/_windows.scss
=> Windows: Match decoration border between Hdy and Gtk

src/widgets/_scales.scss
=> Scales: Fix background for .color

src/widgets/_spinners.scss
Fixes #911 
Also add backdrop state while we're here
=> Spinners: increase opacity

src/_index.scss, src/_overshoot.scss
This is a straight port of the overshoot from the old stylesheet. Works with light and dark styles plus accent colors.
=> Re-add overshoot

src/_overshoot.scss
And desaturate backdrop styles
=> Overshoot: use functions

src/widgets/_switches.scss
=> Switches: Add focus style

data/stylesheet.appdata.xml.in, src/widgets/_headerbars.scss
=> Headerbars: set title font-weight as bold

data/stylesheet.appdata.xml.in, meson.build
=> Release 6.1.1

src/gtk-4.0/widgets/_buttons.scss, src/gtk-4.0/widgets/_checkbuttons.scss, src/gtk-4.0/widgets/_notebooks.scss, src/gtk-4.0/widgets/_switches.scss, src/gtk-4.0/widgets/_views.scss
Space between functions and parentheses is no longer valid syntax
=> GTK4: fix errors about invalid color

data/stylesheet.appdata.xml.in, src/gtk-3.0/widgets/_menus.scss, src/gtk-4.0/widgets/_menus.scss
=> ModelButtons: add margin between checks, radios, and labels

src/gtk-4.0/widgets/_entries.scss
placeholder has its own element now
=> GTK4/Entries: set placeholder color

src/gtk-4.0/widgets/_progressbars.scss
=> GTK4/Progressbars: set min height/width

src/gtk-4.0/widgets/_columnviews.scss, src/gtk-4.0/widgets/_index.scss
Notice rounded corners, no padding, sort indicators:
=> GTK4: add columnview

src/gtk-4.0/widgets/_scrollbars.scss
This just appears to not be a thing anymore at all
=> GTK4/Scrollbars: Remove unused properties

src/gtk-4.0/widgets/_menubars.scss
super tiny element name change
=> GTK4/Menubars: menuitem → item

src/gtk-4.0/widgets/_checkbuttons.scss
=> GTK4/CheckButtons: fix size

src/gtk-4.0/widgets/_buttons.scss
=> GTK4: add margin to fontbutton sep

src/gtk-4.0/widgets/_checkbuttons.scss
=> GTK4/CheckButtons: fix styles for image-button

src/gtk-4.0/widgets/_emojipicker.scss
=> GTK4/EmojiPickers: fix styles

src/gtk-4.0/widgets/_views.scss
Fix text selection style for terminal and add padding to terminal scrolledwindows
=> Gtk4 terminal

src/gtk-4.0/widgets/_entries.scss
* Fix some icon size issues
* Style password entry
=> GTK4/Entries: style password entry

src/gtk-4.0/widgets/_index.scss, src/gtk-4.0/widgets/_settingspages.scss
Add styles for Granite.AbstractSimpleSettingsPage
=> Style SettingsPages

src/gtk-4.0/widgets/_sidebars.scss
Goes with https://github.com/elementary/granite/pull/595
=> Sidebars: style settingssidebar

src/gtk-4.0/widgets/_infobars.scss
Fixes #1177
with optional `frame` class for floating
=> Redesign infobars

src/gtk-4.0/widgets/_dropdowns.scss, src/gtk-4.0/widgets/_index.scss, src/gtk-4.0/widgets/_popovers.scss
styles for dropdowns, like the one in Gtk4 Demo → Clipboard or Gtk4 Demo → Lists → Selections
=> Style Dropdowns

src/gtk-3.0/widgets/_cards.scss, src/gtk-4.0/widgets/_cards.scss
=> Style Paper element

meson.build
Release an initial stable version of the stylesheet so we can get some testing and feedback from app devs
At this point we should have styles for everything in Gtk Widget Factory, Gtk Demo, and Granite 7
=> Release 7.0.0

data/stylesheet.appdata.xml.in
In the interest of https://github.com/elementary/feedback/pull/64
=> AppData: change name and description

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/_headerbars.scss, src/gtk-4.0/widgets/_separators.scss, src/gtk-4.0/widgets/_windowcontrols.scss
* Fixes #1209
* Fix window controls spacing in RTL
* Fix separators in Headerbars
=> Headerbars: fix spacing

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/_infobars.scss
=> Infobars: fix button margin when no close

src/gtk-3.0/widgets/_index.scss, src/gtk-4.0/widgets/_index.scss
Makes the checkerboard effect much more subtle so that it interferes with image previews less
=> Index: make checkerboard much more subtle

src/gtk-4.0/widgets/_headerlabels.scss, src/gtk-4.0/widgets/_index.scss
Tightens up text in https://github.com/elementary/granite/pull/624
=> Headerlabels

src/gtk-4.0/widgets/_lists.scss, src/gtk-4.0/widgets/_popovers.scss
=> Fix heading label padding in lists

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/_scales.scss
=> Scales: correctly style mark labels

data/stylesheet.appdata.xml.in, meson.build
=> Release 7.0.1

src/gtk-4.0/widgets/_headerbars.scss, src/gtk-4.0/widgets/_notebooks.scss, src/gtk-4.0/widgets/_windows.scss
Some of the most glaring things I've noticed, though there's a lot more missing.
=> Fixes for Epiphany

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/_buttons.scss, src/gtk-4.0/widgets/adw/MessageDialog.scss, src/gtk-4.0/widgets/adw/_index.scss
Also make sure .raised overrides .flat and support .destructive
=> Support Adw.MessageDialog

data/stylesheet.appdata.xml.in, meson.build
7.1.0 broke some headerbars so this fixes that :sweat_smile:
=> Release 7.2.0

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/adw/TabGrid.scss, src/gtk-4.0/widgets/adw/TabOverview.scss, src/gtk-4.0/widgets/adw/_index.scss
=> Add Adw TabOverview styles

src/gtk-4.0/widgets/_windows.scss
Should make it pretty obvious which apps aren't Initing Granite :sweat_smile:
=> Windows: hand over window styles to Granite

src/gtk-4.0/widgets/_windows.scss
Reverts elementary/stylesheet#1280
Gotta put these back, fucks up ssd somehow
=> Revert "Windows: hand over window styles to Granite"

src/gtk-4.0/widgets/_views.scss
=> Views: style gridview child

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/_notebooks.scss, src/gtk-4.0/widgets/adw/TabBar.scss, src/gtk-4.0/widgets/adw/ToolbarView.scss
=> Improve tabbar appearance in dark mode

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/adw/AboutWindow.scss, src/gtk-4.0/widgets/adw/Dialog.scss, src/gtk-4.0/widgets/adw/_index.scss
=> Add support for new Adw.Dialog and bottom sheets

src/gtk-4.0/widgets/_stackable_boxes.scss
=> Add support for Adw.OverlaySplitView

src/gtk-4.0/widgets/_popovers.scss
Should be the actual fix for the issue in https://github.com/elementary/granite/pull/736
Fixes #1170
=> Popovers: use border-spacing

src/gtk-4.0/widgets/adw/PreferencesWindow.scss
Fixes crash in https://github.com/elementary/browser/pull/166#issue-3006733960
=> Adw/PreferencesWindow: fix crash in Ephy

src/gtk-4.0/widgets/adw/PreferencesWindow.scss
Probably fixes https://github.com/elementary/fileroller/issues/49
Fixes styles for preferences pages used outside a PreferencesWindow such as bookmarks dialog in Ephy
=> Adw/PreferencesWindow: add some style fixes

data/stylesheet.appdata.xml.in, src/gtk-4.0/widgets/_sidebars.scss
Tested with [Notes](https://github.com/danirabbit/notes/pull/10). Also fixes missing sidebar styles in Papers
=> Sidebars: add support for Adw.NavigationSplitView

src/gtk-3.0/widgets/_checkbuttons.scss, src/gtk-4.0/widgets/_checkbuttons.scss
Required for elementary/settings-desktop#456 and elementary/onboarding#261
=> CheckButtons: Support Latte
